### ISSUE TITLE
Incompatibility with Twig 3

### ISSUE THREAD

**Issue by rogierknoester** [mmucklo/DtcGridBundle#24]
Hi,

It seems like the package is incompatible with Twig 3 because it has removed the `\Twig_Extension` class, which was previously deprecated. During development it doesn't really matter because it is never autoloaded because `Twig\Extension\AbstractExtension` exists
![image](https://user-images.githubusercontent.com/4541046/84004983-aea78e00-a96c-11ea-8296-d276a0856f3a.png)

However, during build time of a Docker image in which composer dumps the autoloader it still tries to load the class, which fails because it is not available in Twig 3 anymore.
![image](https://user-images.githubusercontent.com/4541046/84004920-98013700-a96c-11ea-8e50-31ada05169ff.png)

If a `class_exists` call during autoload dump works, I think that is the easiest solution, i.e. duplicating what you're doing in the `GridSourceCompilerPass::legacyTwigExtension`.
```php
!class_exists('Twig\Extension\AbstractExtension')
``` 
around the 
```php
class TwigExtension extends \Twig_Extension
```
declaration. The file wouldn't ever be loaded unless the compiler pass deems it necessary, with the same if-statement.

If not, it might also be possible to exclude the file from being parsed during classmap generation (https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps).

Let me know and I'll work on a PR :)

**Comment by mmucklo** [comment]
@rogierknoester,

This should be fixed and merged into master.

**Comment by rogierknoester** [comment]
Cheers, I'll try to confirm it soon.

**Comment by er1z** [comment]
I've installed using `dev-master` and problem still persists.

**Comment by mmucklo** [comment]
ok Let me take a look.

**Comment by mmucklo** [comment]
Ok, I saw that both classes were named the same, so I put a class_exists block around the other class, hopefully that will solve it.

**Comment by mmucklo** [comment]
Oh, nevermind, I see the problem, TwigExtensionLegacy contained the same class, so instead it should just contain TwigExtension.

I think it should be fixed now.

**Comment by rogierknoester** [comment]
Saw the thread come in my feed again so decided to test, works flawlessly! Thanks a lot!
